# Generated by Django 5.2 on 2025-04-26 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_company_options_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 4, 26, 20, 44, 57, 65553, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 4, 26, 20, 45, 8, 802705, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gameresults",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 4, 26, 20, 45, 13, 393723, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gameresults",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 4, 26, 20, 45, 15, 350514, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamesession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.CharField(
                choices=[("Action", "ACTION"), ("Puzzle", "PUZZLE"), ("Strategy", "STRATEGY")], max_length=20
            ),
        ),
    ]
