# Generated by Django 5.2 on 2025-04-26 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_customuser_company_remove_customuser_groups_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="participants",
            field=models.ManyToManyField(related_name="game_sessions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "CREATED"),
                    ("InProgress", "IN_PROGRESS"),
                    ("Finished", "FINISHED"),
                    ("Failed", "FAILED"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
