version: '3'

tasks:
  migrate:
    desc: Migrate db
    cmds:
      - uv run python manage.py makemigrations
      - uv run python manage.py migrate

  run:
    desc: Run application
    cmds:
      - docker compose up --build

  lint:
    desc: Run linters (ruff + mypy)
    cmds:
      - uv run ruff check --fix --config=pyproject.toml
      - uv run mypy .

  format:
    desc: Run formatter
    cmds:
      - uv run ruff format --config=pyproject.toml

  update:
    desc: Update dependencies
    cmds:
      - uv lock --upgrade
      - uv sync

  update-win:
    desc: Sync dependencies into Windows venv (run from PowerShell)
    cmds:
      - uv sync --active

  test:
    desc: Run pytest with Django settings
    cmds:
      - uv run pytest apps

  pre-commit:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files

  generate:
    desc: Generate and load test data fixtures
    env:
      ENV: dev
    cmds:
      - uv run python manage.py migrate
      - uv run python manage.py generate_fixtures
      - uv run python manage.py loaddata apps/games/fixtures/test_data.json
