version: '3'

tasks:
  migrate:
    desc: Migrate db
    cmds:
      - docker exec -it game_management_api python manage.py makemigrations
      - docker exec -it game_management_api python manage.py migrate

  run:
    desc: Run application
    cmds:
      - docker compose up --build

  lint:
    desc: Run linters
    cmds:
      - uv run ruff check --fix --config=pyproject.toml

  format:
    desc: Run formatter
    cmds:
      - uv run ruff format --config=pyproject.toml

  update:
    desc: Update dependencies
    cmds:
      - uv lock --upgrade
      - uv sync

  test:
    desc: Run tests with coverage
    cmds:
      - uv run pytest --cov=games --cov-report=term-missing

  pre-commit:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files
