version: '3'

tasks:
  migrate:
    desc: Migrate db
    cmds:
      - docker exec -it game_management_api python manage.py makemigrations
      - docker exec -it game_management_api python manage.py migrate

  run:
    desc: Run application
    cmds:
      - docker compose up --build

  lint:
    desc: Run linters
    cmds:
      - |
        if [ -n "$COMSPEC" ] && [ -x "$COMSPEC" ]; then
          powershell -Command "poetry run ruff check --fix --config=pyproject.toml"
        else
          poetry run ruff check --fix --config=pyproject.toml
        fi

  format:
    desc: Run formatter
    cmds:
      - |
        if [ -n "$COMSPEC" ] && [ -x "$COMSPEC" ]; then
          powershell -Command "poetry run ruff format --config=pyproject.toml"
        else
          poetry run ruff format --config=pyproject.toml
        fi

  update:
    desc: Update dependencies
    cmds:
      - |
        if [ -n "$COMSPEC" ] && [ -x "$COMSPEC" ]; then
          powershell -Command "poetry update"
        else
          poetry update
        fi

  test:
    desc: Run tests with coverage
    cmds:
      - export DJANGO_SETTINGS_MODULE=game_management.settings && pytest --cov=games --cov-report=term-missing
