version: '3'

tasks:
  localrun:
    desc: Run bot locally
    cmds:
      - docker compose -f docker-compose-local.yml up --build

  build:
    desc: Build Docker-container
    cmds:
      - docker compose build

  up:
    desc: Start Docker-containers
    cmds:
      - docker compose up

  down:
    desc: Stop Docker-containers
    cmds:
      - docker compose down

  lint:
    desc: Run linters
    cmds:
      - ruff check --fix --config=pyproject.toml

  format:
    desc: Run formatter
    cmds:
      - ruff format --config=pyproject.toml

  update:
    desc: Update dependencies and sync requirements.txt
    cmds:
      - |
        if [ -n "$COMSPEC" ] && [ -x "$COMSPEC" ]; then
          powershell -Command "poetry update"
          powershell -Command "poetry export -f requirements.txt --without-hashes -o requirements.txt"
        else
          poetry update
          poetry export -f requirements.txt --without-hashes -o requirements.txt
        fi
