# Generated by Django 5.1.7 on 2025-03-23 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_datetime", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="games.game"
                    ),
                ),  # noqa
                ("participants", models.ManyToManyField(related_name="game_sessions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="GameResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("InProgress", "In Progress"),
                            ("Finished", "Finished"),
                            ("Failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),  # noqa
                ("is_completed", models.BooleanField()),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="games.gamesession"
                    ),
                ),  # noqa
            ],
        ),
    ]
