# Generated by Django 5.1.7 on 2025-03-30 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="gameresults",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("InProgress", "In Progress"),
                    ("Finished", "Finished"),
                    ("Filed", "Filed"),
                ],
                max_length=20,
            ),  # noqa
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SuperAdmin", "SuperAdmin"),
                            ("CompanyAdmin", "CompanyAdmin"),
                            ("Participant", "Participant"),
                        ],
                        max_length=20,
                    ),
                ),  # noqa
                (
                    "company",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="games.company"
                    ),
                ),  # noqa
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),  # noqa
            ],
        ),
    ]
