name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        env:
          RUSTUP_HOME: ${{ runner.temp }}/rustup
          CARGO_HOME: ${{ runner.temp }}/cargo
      - name: Add cargo bin to PATH
        run: echo "${{ runner.temp }}/cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: uv sync --all

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
